### ISSUE TITLE
Totals in charts?

### ISSUE THREAD

**Issue by manez** [mjordan/islandora_repository_reports#1]
Just following up on my comment during the Tech Call demo. I'd love to see totals in the charts, as this looks like a colorful way to answer the perennial "how many objects are in my repository?" question.

Number of objects and size of objects are two metrics that come to mind.

**Comment by mjordan** [comment]
@manez I've added a total disk usage report with commit 53f69b46b640b8aa50ec904a3071fac6fb637cd1. When you say "size of objects", did you mean total disk storage used, or did you mean a graph showing ranges of size of objects (e.g., bigger than 1 GB, between 1 GB and 500 MB, between 500 MB and 101 MB, between 100 MB and 50 MB, etc.?

**Comment by manez** [comment]
I think I meant the total disk storage, so 🎊 for that, but a graph breaking it down so you could see what percentage of that total is made up of files from those different size ranges sounds interesting. Is disk storage by mimetype doable?

**Comment by mjordan** [comment]
@manez yes, I think disk storage by mimetype is doable. Maybe a drop-down selector on that report to allow the user to choose Filesystem or MIME Type?

**Comment by mjordan** [comment]
OK, disk usage report lets user choose how to group the output, by filesystem or by MIME type.

**Comment by mjordan** [comment]
@manez OK to close?

**Comment by manez** [comment]
Yes! All good.
