### ISSUE TITLE
Media Use Term IDs

### ISSUE THREAD

**Issue by manez** [mjordan/islandora_repository_reports#14]
This is a bit trivial, but:

![image](https://user-images.githubusercontent.com/2371345/81703895-8d25b600-9443-11ea-98ee-9390f1bcf1d2.png)

Would it be a lot of work to make this use the actual terms instead of node IDs? And a checklist?  I think it would be more user-friendly.

**Comment by mjordan** [comment]
Working on it (already reported in #3, which I'll close). I'm trying to emulate the approach to an autocomplete from https://github.com/Islandora/islandora/blob/8.x-1.x/src/Plugin/Condition/NodeHasTerm.php but haven't had much luck.

**Comment by mjordan** [comment]
@manez do you think a list of checkboxes or an autocomplete would be better UX?

**Comment by manez** [comment]
I prefer checkboxes, since they don't require advanced knowledge of the available results.

**Comment by mjordan** [comment]
OK, thanks, that's useful feedback.

**Comment by mjordan** [comment]
OK, now this report form looks like:

![mime](https://user-images.githubusercontent.com/403918/81769110-9dfd1880-9491-11ea-9e2a-9173f734c364.png)

You'll need to choose terms first time you use it, but they will stick after that.
