### ISSUE TITLE
Provide option in node reports to limit to specific content types

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_repository_reports#28]

**Comment by mjordan** [comment]
Now, each report that counts nodes lets the user select which content types to include using the following form widget:

![contenttypes](https://user-images.githubusercontent.com/403918/82630764-8d8f2100-9ba8-11ea-9850-cf60ea0c10c8.png)

@manez would you mind testing? Just pull in changes to the master branch.

**Comment by manez** [comment]
Tested, everything looks good!

**Comment by mjordan** [comment]
Thanks for testing!
