### ISSUE TITLE
Whitescreen when viewing reports if repository is empty

### ISSUE THREAD

**Issue by dannylamb** [mjordan/islandora_repository_reports#34]
Just installed on a fresh (and empty) islandora-playbook instance.  Got a WSOD with this in the logs

```
Drupal\Core\Database\InvalidQueryException: Query condition 'media__field_media_use.field_media_use_target_id IN ()' cannot be empty. in Drupal\Core\Database\Query\Condition->condition() (line 105 of /var/www/html/drupal/web/core/lib/Drupal/Core/Database/Query/Condition.php).
```

**Comment by dannylamb** [comment]
I stand corrected, getting that all the time even with content.

**Comment by mjordan** [comment]
@dannylamb did this happen when you first visited the reports page  from the "Reports" admin menu, or after you clicked on the "Go" button?

**Comment by mjordan** [comment]
I've added check code around any query conditions that use `IN`. If the list is empty, the plugin returns and empty array and the user should get the message "No [...] data to report on" message. Can you pull in changes to master and test?

**Comment by dannylamb** [comment]
I didn't get to the "Go" button.  I'll test now :+1:

**Comment by dannylamb** [comment]
Yep!  Working now :rocket:

**Comment by mjordan** [comment]
Very good, thanks for finding this.
